### ISSUE TITLE
"For compile it, you need to drag and drop these Dll of your EFT Folder/EFT_Data/Managed:"

### ISSUE THREAD

**Issue by nightimegames** [TheWWorld/NoNameCheatV2#1]
drag and drop these where?

**Comment by bitcoiner32** [comment]
ok I can help

**Comment by bitcoiner32** [comment]
firstly you need those files from your path to your eft game folder it should be "C:\Battlestate Games\EFT\EscapeFromTarkov_Data\Managed" and you can find them files there and you put them in the properties folder so here after extract "\NoNameCheatV2-master\NoNameCheatV2-master\NNCV2\Properties" ok then you open the .sln file in visual studio add junk code and other stuff to remain undetected compile it and get a custom injector and boom you done  anything you would like to add @TheWWorld  :)

**Comment by bitcoiner32** [comment]
also if your reading this @TheWWorld can you help me with the custom injector pretty please that would be lovely and how to bypass the Sclient and with the junk code ill pm but encase you don't get that just pm me thx very much <3

**Comment by TheWWorld** [comment]
> 
> 
> also if your reading this @TheWWorld can you help me with the custom injector pretty please that would be lovely and how to bypass the Sclient and with the junk code ill pm but encase you don't get that just pm me thx very much <3

There is a subject in UC for Bypassing methods.
And for the custom injector i use the MInject Library (you can use MInjector, take the source and modify at your convenience 🦊 )

**Comment by bitcoiner32** [comment]
> There is a subject in UC for Bypassing methods.
I don't get that UC??????
also I know how to customize the minjector but not what to do wit please help as this sort of coding isn't where my ability is have you got like avideo tutorial or if you want you show me how to do it and I make a tutorial on YT @TheWWorld

**Comment by TheWWorld** [comment]
> 
> 
> > There is a subject in UC for Bypassing methods.
> > I don't get that UC??????
> > also I know how to customize the minjector but not what to do wit please help as this sort of coding isn't where my ability is have you got like avideo tutorial or if you want you show me how to do it and I make a tutorial on YT @TheWWorld

Please create a issues for that, one things per issues, it's more readable for everyone.
